/**
 * Edit this file to rebrand the entire site. All values here are PUBLIC.
 * Keep database passwords and service-role keys in .env, never in this file.
 * Presale tiers and SOL reference prices are fixed, not a live market feed.
 * Rebuild after changes. Chart snapshots are generated by the backend daily.
 */
export const config = {
  brand: {
    name: "Astro Bull",
    ticker: "ASTROBULL", // No $ prefix; display symbols are derived below.
    tagline: "No gravity. All attitude.",
    headline: ["BULLISH ON", "OUTER SPACE."],
    description:
      "One bull. Zero gravity. A whole herd of cosmic chaos. Grab your tokens and get in, loser. We’re going to space.",
    astronaut: "/bull-astronaut-floating.png",
    logo: "/astro-bull-logo.png", // Optional logo path; empty uses the orbit icon next to your name.
    favicon: "/favicon.ico",
  },
  site: {
    url: "https://astrobull.space",
    description:
      "An astronaut-inspired Solana meme token. Explore the presale, claim your airdrop, and join the herd.",
    shareImage: "/hero-social-preview.jpg",
    accent: "#53f02b",
    background: "#060a08",
    ink: "#f3f6f1",
    secondary: "#a8c5b4",
    pink: "#ffadd2",
  },
  network: {
    name: "Solana",
    currency: "SOL",
    cluster: "mainnet-beta", // "mainnet-beta" | "devnet" | "testnet"
    explorerUrl: "https://solscan.io",
    presaleWalletAddress: "7YWwFTA5E439LnTtQyuACkNmpgtDGBvh1HuDDTabJxnX",
    tokenAddress: "", // Empty until a token is deployed.
  },
  presale: {
    // Manual transfers: enter an amount, copy network.presaleWalletAddress,
    // then send from your own wallet on network.cluster.
    enabled: true,
    stage: 1,
    stageName: "Early orbit",
    startsAt: "2026-10-01T00:00:00.000Z",
    endsAt: "2026-11-01T00:00:00.000Z",
    solPriceUsd: 180,
    minSol: 0.2,
    maxSol: 10,
    defaultSol: 1,
    // Custom amounts interpolate between these exact allocation points.
    tiers: [
      { sol: 0.2, tokens: 20_000_000 },
      { sol: 1, tokens: 200_000_000 },
      { sol: 2, tokens: 500_000_000 },
      { sol: 5, tokens: 650_000_000 },
      { sol: 10, tokens: 2_000_000_000 },
    ],
  },
  token: {
    totalSupply: 10_000_000_000,
    decimals: 6,
    allocations: [
      { name: "Presale", percent: 80, color: "#bcff3b" },
      { name: "Liquidity", percent: 10, color: "#c5b2ff" },
      { name: "Community", percent: 5, color: "#ffadd2" },
      { name: "Marketing", percent: 3, color: "#ffda64" },
      { name: "Team", percent: 2, color: "#8ee2d3" },
    ],
  },
  airdrop: {
    enabled: true,
    rewardTokens: 200_000,
    poolTokens: 500_000_000,
    title: ["FREE TOKENS.", "BIG BULL ENERGY."],
    description:
      "A little something for the herd. Drop your Solana wallet below and claim your allocation.",
  },
  market: {
    title: "THE VIBE CHART.",
    subtitle: "Imaginary candles. Very real bull energy.",
    // Server simulation settings. Clients receive series from /api/market/chart.
    // Each snapshot stays fixed until midnight in this timezone.
    snapshotTimeZone: "Africa/Lagos",
    simulationSeed: "astro-bull-market-v1",
    referencePriceUsd: 0.0000018,
    referenceVolumeUsd: 2450,
    ranges: [
      { label: "1H", hours: 1 },
      { label: "24H", hours: 24 },
      { label: "7D", hours: 168 },
    ],
  },
  roadmap: [
    {
      phase: "01",
      title: "Assemble the herd",
      status: "WE ARE HERE",
      description:
        "Launch the presale, open the airdrop, and find our fellow space weirdos.",
      color: "#bcff3b",
    },
    {
      phase: "02",
      title: "Prepare for chaos",
      status: "UP NEXT",
      description:
        "Grow the community. Drop the memes. Get the token ready for its big entrance.",
      color: "#c5b2ff",
    },
    {
      phase: "03",
      title: "Leave the planet",
      status: "THE MISSION",
      description:
        "Launch the token, explore new partnerships, and let the herd lead the way.",
      color: "#ffadd2",
    },
  ],
  links: {
    x: "https://x.com/AstroBullSOL",
    telegram: "https://t.me/AstroBullSOL",
    discord: "", // Empty links are hidden.
    whitepaper: "",
  },
  navigation: [
    { label: "Presale", href: "#presale" },
    { label: "How to buy", href: "#how-to-buy" },
    { label: "Airdrop", href: "#airdrop" },
    { label: "Chart", href: "#market" },
    { label: "Tokenomics", href: "#tokenomics" },
    { label: "Roadmap", href: "#roadmap" },
  ],
  copy: {
    heroBadge: "SOMEONE GAVE THE BULL A SPACESUIT",
    missionLabel: "NO GRAVITY. ALL ATTITUDE.",
    communityTitle: "LESS LURKING. MORE BULL.",
    communityDescription: "The spaceship has Wi-Fi. Come hang with the herd.",
    footerNote: "Stay bullish, earthling.",
    steps: [
      {
        title: "Pick your fuel",
        description:
          "Choose your SOL amount. We’ll do the token math. You do the dreaming.",
      },
      {
        title: "Copy the wallet",
        description:
          "Copy the full presale wallet address from the purchase card. Check the displayed network.",
      },
      {
        title: "Send your SOL",
        description:
          "Open your wallet, paste the address, and send your chosen SOL amount. Keep your transaction signature.",
      },
    ],
    faqs: [
      {
        question: "How do I buy presale tokens?",
        answer:
          "Enter a SOL amount to see the token estimate. Copy the presale wallet address, then send the selected amount from your own wallet on the network shown in the purchase card.",
      },
      {
        question: "How is my allocation calculated?",
        answer:
          "The displayed SOL tiers set your token allocation. Custom amounts are calculated proportionally between the two surrounding tiers. USD figures use the configured SOL reference price; the simulated market chart does not change your allocation.",
      },
      {
        question: "How do I check my transfer?",
        answer:
          "Find the transaction signature in your wallet’s activity and open it in the explorer for the displayed network. Copying the address does not confirm payment. This page does not automatically verify deposits or issue tokens.",
      },
      {
        question: "Can I claim the airdrop more than once?",
        answer:
          "Each Solana wallet can claim one allocation while the pool lasts. Claims are saved, but no real tokens are transferred. You never need to share a seed phrase or sign a transaction.",
      },
    ],
  },
};

export const symbol = `$${config.brand.ticker}`;
export const networkLabel = `${config.network.name} ${config.network.cluster === "mainnet-beta" ? "Mainnet" : config.network.cluster.charAt(0).toUpperCase() + config.network.cluster.slice(1)}`;
export const presaleSupply =
  (config.token.totalSupply *
    (config.token.allocations.find(
      (allocation) => allocation.name === "Presale",
    )?.percent ?? 0)) /
  100;

export function quoteTokens(sol: number): number {
  if (validateAmount(sol)) return 0;
  const tiers = config.presale.tiers;
  const upperIndex = tiers.findIndex((tier) => sol <= tier.sol);
  if (upperIndex < 0) return 0;
  const upper = tiers[upperIndex];
  if (sol === upper.sol) return upper.tokens;
  const lower = tiers[upperIndex - 1];
  if (!lower) return 0;
  // Integer lamports and token units avoid float rounding at tier boundaries.
  const precision = 10 ** config.token.decimals;
  const amountLamports = BigInt(Math.round(sol * 1e9));
  const lowerLamports = BigInt(Math.round(lower.sol * 1e9));
  const upperLamports = BigInt(Math.round(upper.sol * 1e9));
  const lowerUnits = BigInt(Math.round(lower.tokens * precision));
  const deltaUnits = BigInt(
    Math.round((upper.tokens - lower.tokens) * precision),
  );
  return (
    Number(
      lowerUnits +
        ((amountLamports - lowerLamports) * deltaUnits) /
          (upperLamports - lowerLamports),
    ) / precision
  );
}

export function effectiveTokenPriceUsd(sol: number): number {
  const tokens = quoteTokens(sol);
  return tokens > 0 ? (sol * config.presale.solPriceUsd) / tokens : 0;
}

// Compatibility values for the old database's scalar pricing/cap columns.
// Full tier data in site_config is authoritative for allocations.
export const referenceTokenPriceUsd = effectiveTokenPriceUsd(
  config.presale.defaultSol,
);
export const presaleCapacityUsd =
  presaleSupply *
  Math.min(
    ...config.presale.tiers.map(
      (tier) => (tier.sol * config.presale.solPriceUsd) / tier.tokens,
    ),
  );

export function formatCompactTokens(tokens: number) {
  return new Intl.NumberFormat("en-US", {
    notation: "compact",
    maximumFractionDigits: 2,
  }).format(tokens);
}

export function validateAmount(sol: number): string | null {
  if (!Number.isFinite(sol) || sol <= 0) return "Enter a valid SOL amount.";
  if (sol < config.presale.minSol)
    return `Minimum purchase is ${config.presale.minSol} SOL.`;
  if (sol > config.presale.maxSol)
    return `Maximum purchase is ${config.presale.maxSol} SOL.`;
  if (Math.abs(sol * 1e9 - Math.round(sol * 1e9)) > 0.00001)
    return "Use at most 9 decimal places for SOL.";
  return null;
}

export function saleStatus(now = Date.now()): "upcoming" | "open" | "closed" {
  if (!config.presale.enabled || now >= Date.parse(config.presale.endsAt))
    return "closed";
  if (now < Date.parse(config.presale.startsAt)) return "upcoming";
  return "open";
}

export function formatNumber(value: number, maximumFractionDigits = 2) {
  return new Intl.NumberFormat("en-US", { maximumFractionDigits }).format(
    value,
  );
}

export function formatUsd(value: number) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: value > 0 && value < 0.01 ? 8 : 2,
  }).format(value);
}

export function shortAddress(address: string) {
  return `${address.slice(0, 5)}…${address.slice(-5)}`;
}

export default config;
